#!/bin/sh -e
# Run the autotools bootstrap sequence to create the configure script

# bootstrap the autotools
set -x
aclocal
autoconf
autoheader
automake --foreign --add-missing --copy

# AM_MAINTAINER_MODE requires SVN users provide --enable-maintainer-mode
# otherwise the documentation will fail to build due to missing version.texi
echo "Bootstrap complete; you can './configure --enable-maintainer-mode ....'"
